pub const VERIFICATION_TYPE_DIGEST: u8 = 0;
pub const VERIFICATION_TYPE_DIGEST_SIGNATURE: u8 = 1;
pub const VERIFICATION_TYPE_SIGNATURE: u8 = 2;
pub const VERIFICATION_TYPE_BLOCK_WITH_PROOFS: u8 = 10;
